---
name: Charts (Reusable)

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: false
        type: string
        default: ${{ github.ref }}

permissions:
  contents: read

jobs:
  charts:
    runs-on: ubuntu-latest
    name: Charts
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Install Deps
        uses: ./.github/actions/setup-deps

      - name: Build Charts
        shell: bash
        run: |
          make charts

      - name: Collect Chart Artifacts
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/artifacts/charts
          mv charts/*.tgz ${{ github.workspace }}/artifacts/charts/

      - id: upload-chart-artifacts
        name: Upload Chart Tarball
        uses: actions/upload-artifact@v5
        with:
          name: charts
          retention-days: 7
          if-no-files-found: error
          path: ${{ github.workspace }}/artifacts/charts/*.tgz
